py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8
  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9

  services:
  - redis:latest

  script:
  - pip install tox
  - tox -e format,mypy,py39,pep8,setuppy,manifest,redis
